# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fishii' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fishii

  pod 'OneSignal', '~> 1.13.3'

  #target 'FishiiTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end
